name: Robotics Group @ University of Montreal
description: The Robotics and Embodied AI Lab @ U de Montreal
url: http://montrealrobotics.github.io

exclude: [bibble, README.md, Makefile, screenshot.png]

# colorize code snippets with the pygments module
highlighter: rouge

# The path structure for blog posts.
permalink: /blog/:year/:month/:day/:title.html

# Sections on the "people" page.
roles:
  - key: faculty
    name: Faculty
  - key: staff
    name: Staff
  - key: postdoc
    name: Researchers
  - key: masters
    name: Master's Students
  - key: phd
    name: PhD Students
  - key: intern
    name: Interns
  - key: intern-alum
    name: Past Interns
  - key: collab
    name: Collaborators
  - key: alum
    name: Alumni

# Number of news stories on the front page.
front_page_news: 8

# Number of old projects on the front page
front_page_old_projects: 4

# Base pathname for links.
base: ''

# make pages for the _projects folder
collections:
  projects:
    output: true

# Navigation bar links.
navigation:
  - title: Home
    link: /
  - title: People
    link: /people.html
  - title: Research
    link: /research.html
  - title: Publications
    link: /publications/
  - title: Contact
    link: /contact.html
  - title: Blog
  - link: /blog.html

# Includes
include: ['_pages']

gems:
    - jekyll-paginate
    - jekyll/scholar
    - jemoji


# Build settings
markdown: kramdown
highlighter: pygments

# Jekyll-Scholar
scholar:

  style: apa
  locale: en

  sort_by: year
  order: descending

  source: /_bibliography/
  bibliography: pubs.bib
  bibliography_template: bib

  replace_strings: true
  join_strings: true

  details_dir: bibliography
  details_layout: bibtex.html
  details_link: Details

  query: "@*"

jquery_version: "1.12.4"
katex_version: "0.7.1"
anchorjs_version: "3.2.2"